export * from './person.module';
export * from './shared';
export * from './list';
export * from './insert';
export * from './interview';
export * from './interview-list';
export * from './interview-view';
export * from './laborer-list';
export * from './person-routing.module';